### ISSUE TITLE
Make warnings of empty-line-before rules?

### ISSUE THREAD

**Issue by wimhendrikx** [kutsan/stylelint-config-clean-order#12]
The empty-line-before rules (declaration and at-rule) are shown as errors. Should be warnings no?

**Comment by kutsan** [comment]
I'm sorry this took a while to respond. I'm actually still thinking about this one.

We can change the severity of these to warning but this would introduce an inconsistent behavior with [other style rules that comes with popular config packages](https://github.com/stylelint/stylelint-config-standard/blob/17401260e55232993fa45ac5533e832a7124fb74/index.js). I thought it would be better to leave them as is. What do you think?

**Comment by wimhendrikx** [comment]
Okay, fine by me. I can always overwrite it in my own config.

**Comment by kutsan** [comment]
I thought about this again and in the end they're stylistic rules so it make sense to use `warning` level severity. I published a new version with these changes.
