### ISSUE TITLE
Move to `stylelint-order` 6.0

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [kutsan/stylelint-config-clean-order#18]
(shamelessly copied from the [same issue](https://github.com/stormwarning/stylelint-config-recess-order/issues/332) in [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order))

Stylelint just released 6.0. There are no [big changes](https://github.com/hudochenkov/stylelint-order/releases) (mostly Node.js deprecation), the transition should be simple.

**Comment by kutsan** [comment]
It is published with `v3.0.0`. Thanks for the heads up!

**Comment by ehoogeveen-medweb** [comment]
Thanks! By the way, all rules that enforce stylistic conventions were [https://github.com/stylelint/stylelint/blob/main/docs/user-guide/rules.md#deprecated](deprecated) in `stylelint` version 15, and that includes `declaration-empty-line-before` and `at-rule-empty-line-before` (`stylelint-config-prettier` is also considered unnecessary as of `stylelint` version 15 and won't accept it as a peer dependency).

I haven't tried updating yet so I don't know if this config causes warnings, but they will be removed entirely in `stylelint` version 16. So you may have to give up on the formatting part of this config unless you can handle it a different way.

**Comment by kutsan** [comment]
Thanks Emanuel. I'm aware of the deprecations and I was thinking removing the formatting rules with a major release as soon as possible. Thanks again!

**Comment by kutsan** [comment]
FYI, they're removed with `v4.0.0` release. 👋
