### ISSUE TITLE
Rules `declaration-empty-line-before` and `at-rule-empty-line-before` are not actually deprecated

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [kutsan/stylelint-config-clean-order#19]
My apologies, I misread https://github.com/stylelint/stylelint/blob/main/docs/user-guide/rules.md#deprecated and thought these rules were deprecated along with the other stylistic rules, but it appears that they were not! [1]

As a result, version 4 of this config no longer adds these empty lines, causing `order/properties-order` warnings.

Since these were the only changes between version 3 and version 4, perhaps you could simply unpublish version 4?

[1] In my defense, there isn't a lot of separation between the sections...

**Comment by kutsan** [comment]
Ops, I may have misread it too but there is no problem, thanks for letting me know. I'll revert the changes and release a new version as soon as I get home. I also didn't pay attention to separation of the sections, as you said there isn't really much visual indication between them. Thanks again ❤️

**Comment by kutsan** [comment]
I published a new version with reverted changes. I also changed their severity levels to `warning`. Thanks!
