### ISSUE TITLE
Sometime At-rule include needs to be placed before declarations

### ISSUE THREAD

**Issue by tkimvu** [kutsan/stylelint-config-clean-order#24]
In some content blocks https://sass-lang.com/documentation/at-rules/mixin/#content-blocks @include rule need before declarations to override their values.

**Comment by kutsan** [comment]
Hello Trần, I would greatly appreciate it if you could share the reason behind the closure of the issue. I think the case you're referring is valid and we can remove the `include` at-rule from order list if the problem is still persisting.
