### ISSUE TITLE
I am confused about how to remove the empty lines.

### ISSUE THREAD

**Issue by Erimus-Koo** [kutsan/stylelint-config-clean-order#26]
## My Settings

package.json
```
{
	"devDependencies": {
		"stylelint": "^15.10.3",
		"stylelint-config-clean-order": "^5.2.0"
	}
}
```

.stylelintrc.json
```
{
  "extends": "stylelint-config-clean-order",
  "rules": {
        "at-rule-empty-line-before": [ "always", {
          "except": [
            "blockless-after-same-name-blockless",
            "first-nested"
          ],
          "ignore": ["after-comment"]
        } ],
          "ignore": [
            "after-comment",
            "inside-single-line-block"
          ]
        } ],
  }
}
```

VSCode settings.json
```
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "stylelint.packageManager": "pnpm",
	"editor.codeActionsOnSave": {
		"source.fixAll.stylelint": true
	},
```

## My Problems

After pressing the shortcut to "Save" the file:
1. The "clean order" is worked.
2. The stylelint's settings worked, and the empty lines between the properties have been removed.
3. However, the warning continues to appear.
<img width="285" alt="image" src="https://github.com/kutsan/stylelint-config-clean-order/assets/17139670/b5c6cdc0-55e7-40ed-970e-1b2a79d3e39c">

As a beginner, although I saw in the readme how to remove empty lines, but not sure where to add that piece of code.

Are there some suggestions?

## What I want

1. Remove empty lines between properties.
2. Keep only 1 line before the selector (If use your default setting, multiple empty lines before the selector won't be removed).

**Comment by kutsan** [comment]
Hello Erimus, I appreciate your feedback, but this is the intended behavior. The presence of empty lines between properties serves to enhance the visual distinction, making it easier to read and organize property groups. I do acknowledge that this is a subjective matter, but, in my opinion, it greatly simplifies CSS refactoring.

While it's possible to [customize](https://github.com/kutsan/stylelint-config-clean-order?tab=readme-ov-file#customization) this behavior, please note that the removal of empty lines is not currently supported. I aim to maintain a minimal configuration to avoid unnecessary complexity. Additionally, implementing user options through the stylelint API would require creating another variant, such as [error](https://github.com/kutsan/stylelint-config-clean-order?tab=readme-ov-file#severity-options), which I'd prefer to avoid.

**Comment by Erimus-Koo** [comment]
Keeping empty lines between properties is acceptable to me.

But if the multi-empty lines before the selectors could be removed with auto-fix by Stylelint?

**Comment by kutsan** [comment]
I've been using `prettier` alongside with `stylelint` to get better results. What you are suggesting is out of scope of this config and stylelint-order plugin. I advise you to consider utilizing a code formatter such as prettier.

**Comment by edwinbradford** [comment]
@Erimus-Koo  and for anyone else that asks about this, it's actually very easy.

Replace your `.stylelintrc.json` with a `.stylelintrc.js` file then you can just copy the example and it will work, there is no benefit I can think of to using JSON over JavaScript. The syntax will need to change from JSON to JavaScript but a child could do it. On the Stylelint website in the [Configure](https://stylelint.io/user-guide/configure) section the syntax you need to follow is the _CommonJS example_ (at the date of this post).

Here is my configuration as an example.
````
/**
 * Remove line breaks from stylelint-config-clean-order
 *
 * @see https://github.com/kutsan/stylelint-config-clean-order
 */
const { propertyGroups } = require("stylelint-config-clean-order")
const propertiesOrder = propertyGroups.map((properties) => ({
  noEmptyLineBetween: true,
  emptyLineBefore: "never", // Don't add empty lines between order groups.
  properties,
}))

module.exports = {
  overrides: [
    {
      files: ["**/*.scss"],
      customSyntax: "postcss-scss",
    },
  ],
  extends: [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-config-clean-order",
  ],
  ignoreFiles: [
    "**/dist/style.css",
    "**/_normalize.css",
  ],
  rules: {
    "no-descending-specificity": null,
    "property-no-unknown": null,
    "block-no-empty": null,
    "color-named": null,
    "length-zero-no-unit": null,
    "font-weight-notation": "numeric",
    "shorthand-property-no-redundant-values": null,
    "selector-max-compound-selectors": null,
    "selector-class-pattern": null,
    "selector-max-id": 1,
    "selector-no-qualifying-type": null,
    "at-rule-disallowed-list": null,
    "max-nesting-depth": null,
    "function-name-case": "lower",
    "selector-type-case": "lower",
    "value-keyword-case": [
      "lower",
      {
        camelCaseSvgKeywords: true,
      },
    ],
    "alpha-value-notation": null,
    "color-function-notation": null,
    "color-hex-length": null,
    "custom-property-empty-line-before": [
      "never",
      {
        ignore: ["after-comment"],
      },
    ],
    "rule-empty-line-before": [
      "always-multi-line",
      {
        ignore: ["after-comment", "inside-block"],
      },
    ],
    "comment-empty-line-before": [
      "always",
      {
        ignore: ["after-comment"],
      },
    ],
    "font-family-name-quotes": "always-unless-keyword",
    "declaration-block-no-redundant-longhand-properties": null,
    "scss/at-function-pattern": null,
    "scss/comment-no-empty": null,
    "scss/dollar-variable-colon-space-after": "always",
    "scss/dollar-variable-empty-line-before": [
      "never",
      {
        ignore: ["after-comment"],
      },
    ],
    "scss/dollar-variable-pattern": null,
    "scss/double-slash-comment-empty-line-before": null,
    "scss/double-slash-comment-whitespace-inside": "always",
    "scss/percent-placeholder-pattern": null,
    "order/properties-order": [
      propertiesOrder,
      {
        severity: "warning",
        unspecified: "bottomAlphabetical",
      },
    ],
  },
}
````
