### ISSUE TITLE
No support for stylelint v16

### ISSUE THREAD

**Issue by bgonp** [kutsan/stylelint-config-clean-order#27]
[Stylelint 16.0.0](https://github.com/stylelint/stylelint/releases/tag/16.0.0) was released a month ago but this project doesn't support it yet. Looks like everything is working as expected, didn't see any breaking change in the v16, but we can see a warning when installing dependencies and it could be annoying:

```
stylelint is listed by your project with version 16.1.0, which doesn't satisfy what stylelint-config-clean-order (p9b657) and other dependencies request (^14.0.0 || ^15.0.0).
```

The reason is the `stylelint-order` dependency requiring `^6.0.2` which doesn't support stylelint@16.
On `styleling-order@6.0.4` they [added support for stylelint@16](https://github.com/hudochenkov/stylelint-order/releases/tag/6.0.4), so this problem doesn't happen in a fresh installation, but in my case I can see the warning message when installing using my _old_ lock file.

I'll take the liberty to send a quick PR updating it, feel free to discard it in case the solution is not that easy.

**Comment by kutsan** [comment]
Thanks for the detailed explanation and addressing the issue with a pull request. PR is merged and published with [`v5.3.0`](https://github.com/kutsan/stylelint-config-clean-order/releases/tag/v5.3.0). Thanks again!
