### ISSUE TITLE
seems -webkit-line-clamp is missing in the text group

### ISSUE THREAD

**Issue by axten** [kutsan/stylelint-config-clean-order#35]
seems -webkit-line-clamp is missing in the text group

**Comment by kutsan** [comment]
Thanks @axten, I've added `line-clamp` property in https://github.com/kutsan/stylelint-config-clean-order/commit/43c7776fc094749d7e35799c4b7eaebc3979545d and it's published with [v6.1.0](https://github.com/kutsan/stylelint-config-clean-order/releases/tag/v6.1.0).

**Comment by axten** [comment]
that was blazing fast!
thank you!
