### ISSUE TITLE
dollar-variables should be declared before include

### ISSUE THREAD

**Issue by mdizo** [kutsan/stylelint-config-clean-order#7]
When working with SCSS, `@mixin`s are often fed dollar-variables so `@include`s should come after when dollar-variables are defined.

https://github.com/kutsan/stylelint-config-clean-order/blob/ea15c93cd1392eb93d1a65c50d70a941f74196c4/src/index.js#L44-L62

**Comment by kutsan** [comment]
Yes, you're right. It's fixed in https://github.com/kutsan/stylelint-config-clean-order/commit/305503979657680b78f4b06fe51adadfe1a17097. Published with version `v1.0.0`. Sorry it took a while to fix this, I couldn't find time because of work.
