### ISSUE TITLE
Set severty as "warning"?

### ISSUE THREAD

**Issue by wimhendrikx** [kutsan/stylelint-config-clean-order#9]
I find "error" a bit too harsh for bad properties order.

When I am creating my styles I firstly don't care about the order and what to see if I make real errors. As a last step I let my linter auto-fix my code.

**Comment by kutsan** [comment]
Thanks Wim, you're right. I use the same workflow and it does make sense to use warning severity. This is added in https://github.com/kutsan/stylelint-config-clean-order/commit/58ff866b37afe6bf703255cc10625f0f5de47990 and published with `v2.0.0` version. Thanks again!
